//! Restricted build: precompiled policy pack, no runtime toolchain.
//!
//! A *profile* is a policy compiled into this binary at build time and given
//! a name (for example `security` or `deny-all`). A restricted build ships
//! only profiles: it has no policy compiler, so it cannot accept policy
//! source at run time.
//!
//! Materializes each baked evaluator executable to disk and pre-installs every curated
//! profile into the policy registry keyed by its content hash. A client's
//! `SetPolicy(bind_profile_name)` selects the pre-installed entry and binds
//! the precompiled evaluator without a runtime policy compiler.
//! Custom policy uploads (unknown content hash) are rejected by `PolicyService`
//! in restricted mode.
//!
//! ## Self-disable hardening (policy lock)
//!
//! The pack deliberately excludes any permissive profile (`allow-all`): if it
//! were baked, a `SetPolicy` carrying verbatim allow-all source would dedup-hit
//! the pre-installed entry and bind it *before* the restricted-reject is
//! reached, disabling enforcement for the caller's own session. To close that,
//! [`build_engine`] returns the set of content hashes of ALL baked curated
//! profiles, which the binary feeds to `PolicyService::with_policy_lock` so the
//! only policies a session can bind are the curated profiles baked at startup
//! (currently `security` + `deny-all`; `allow-all` is deliberately excluded). A
//! caller may switch among curated profiles by name but cannot bind a softer one.
//!
//! ## Trust boundary (read this before deploying)
//!
//! The policy lock is an **in-process** mitigation. The policed agent runs as
//! the same OS user as the engine it launched, and per-RPC auth can't keep a
//! same-user caller off a loopback socket — so the lock stops the *clean*
//! in-band self-disable (binding allow-all), but a same-user attacker can still
//! `SIGKILL` the engine, replace its binary on disk, or rebind its socket. The
//! robust deployment runs `sasy serve` as a **separate, dedicated OS user**
//! (e.g. a systemd unit with `User=sasy`, or a distinct service account) that
//! the agent's user cannot signal, replace, or impersonate. That — not the
//! lock — is what fully closes the kill→respawn-with-allow-all vector.

use std::path::PathBuf;
use std::sync::Arc;

use anyhow::{Context, Result};
use sasy_graph::GraphStore;
use sasy_policy::session_evaluator::EvaluatorFactory;
use sasy_policy::Engine;
use sasy_policy::EvaluatorEngine;
use tracing::info;

// Generated by build.rs from SASY_POLICY_PACK (empty when unset).
include!(concat!(env!("OUT_DIR"), "/baked_pack.rs"));

const TENANT: &str = "default";

/// True if any profiles are baked in (i.e. this is a real release build).
pub fn has_pack() -> bool {
    !BAKED_PROFILES.is_empty()
}

fn make_factory(elf: PathBuf, program: String) -> EvaluatorFactory {
    use sasy_policy::evaluator::manager::EvaluatorProcess;
    Arc::new(move || {
        EvaluatorProcess::souffle(elf.clone(), program.clone())
            .map(|e| Arc::new(e) as Arc<dyn sasy_policy::Evaluator>)
            .map_err(|e| {
                sasy_policy::EvaluatorError::InitError(format!(
                    "restricted Soufflé subprocess: {e}"
                ))
            })
    })
}

/// Wrap `factory` in the engine this build serves from, with the operator's
/// decisions installed.
///
/// `policy_service_config` is the same value the binary hands
/// `PolicyService`. Both paths that load a persisted policy — the eager
/// replay done by the service at boot, and the lazy install the session map
/// does on first dispatch — consult it, and they must consult the same one.
/// Leaving it off here would not disable the gate; it would silently give the
/// lazy path `PolicyServiceConfig::default()` (custom C++ functor source from
/// non-admin callers refused) while the eager path used what the operator
/// asked for. It is a parameter rather than an optional builder step so the
/// call site cannot omit it.
fn engine_with_config(
    factory: EvaluatorFactory,
    graph: Arc<GraphStore>,
    deadlines: sasy_policy::session_evaluator::EvaluationDeadlines,
    policy_service_config: sasy_policy::service::PolicyServiceConfig,
) -> EvaluatorEngine {
    EvaluatorEngine::with_deadlines(factory, "souffle".to_string(), graph, deadlines)
        .with_policy_service_config(policy_service_config)
}

/// Materialize the baked pack to `<data_dir>/policy-pack/` and build an engine
/// with every curated profile pre-installed (default profile = tenant default).
///
/// Returns the engine and the **set of content hashes of all baked curated
/// profiles** — the value the binary passes to `PolicyService::with_policy_lock`
/// so the only bindable policies are the curated baked profiles, never a softer
/// one (see the module docs).
pub fn build_engine(
    graph: Arc<GraphStore>,
    data_dir: &str,
    deadlines: sasy_policy::session_evaluator::EvaluationDeadlines,
    policy_service_config: sasy_policy::service::PolicyServiceConfig,
) -> Result<(Arc<EvaluatorEngine>, std::collections::HashSet<String>)> {
    if BAKED_PROFILES.is_empty() {
        anyhow::bail!(
            "restricted build has no baked policy pack — rebuild with SASY_POLICY_PACK=<dir>"
        );
    }
    let pack_dir = std::path::Path::new(data_dir).join("policy-pack");
    std::fs::create_dir_all(&pack_dir).context("create policy-pack dir")?;

    // Materialize each baked evaluator executable. The runtime uses these
    // compiled policies directly; it does not materialize .dl source or
    // invoke a policy compiler.
    let mut materialized: Vec<(&'static BakedProfile, PathBuf)> = Vec::new();
    for p in BAKED_PROFILES {
        let elf_path = pack_dir.join(format!("{}.evaluator", p.name));
        std::fs::write(&elf_path, p.evaluator)
            .with_context(|| format!("write {}", elf_path.display()))?;
        #[cfg(unix)]
        {
            use std::os::unix::fs::PermissionsExt;
            std::fs::set_permissions(&elf_path, std::fs::Permissions::from_mode(0o755))?;
        }
        materialized.push((p, elf_path));
    }

    let default_profile = materialized
        .iter()
        .find(|(p, _)| p.is_default)
        .or_else(|| materialized.first())
        .map(|(p, _)| *p)
        .expect("non-empty pack");
    // The lock allows binding ANY baked curated profile (by hash or by name);
    // the pack excludes allow-all, so every baked hash is safe. The binary feeds
    // this set to PolicyService::with_policy_lock (see module docs).
    let locked_hashes: std::collections::HashSet<String> = BAKED_PROFILES
        .iter()
        .map(|p| p.content_hash.to_string())
        .collect();
    let default = materialized
        .iter()
        .find(|(p, _)| p.name == default_profile.name)
        .map(|(p, elf)| make_factory(elf.clone(), p.program.to_string()))
        .expect("default profile present");

    let engine = Arc::new(engine_with_config(
        default,
        graph,
        deadlines,
        policy_service_config,
    ));

    // Pre-install every profile keyed by content hash so SetPolicy dedup-hits.
    for (p, elf) in &materialized {
        let factory = make_factory(elf.clone(), p.program.to_string());
        let mode = if p.is_default {
            sasy_policy::engine::InstallMode::Default
        } else {
            sasy_policy::engine::InstallMode::Variant
        };
        let policy_id = engine
            .install_policy(TENANT, p.content_hash, factory, "souffle".to_string(), mode)
            .with_context(|| format!("pre-install profile {}", p.name))?;
        // Denial messages come from the compiled evaluator's DenialReason
        // relation (baked into the executable); no .dl source is parsed at runtime. The
        // curated profiles don't annotate IsAuthorized, so the rule-metadata
        // (NOT_ALLOWLISTED enrichment) path has nothing to add here regardless.
        // Index the profile name so a client can bind it via
        // SetPolicy(bind_profile_name) — no source, no content hash, just the name.
        engine.register_profile_name(TENANT, p.name, &policy_id);
        info!(
            profile = p.name,
            default = p.is_default,
            "baked profile pre-installed"
        );
    }

    info!(
        count = BAKED_PROFILES.len(),
        default = DEFAULT_PROFILE,
        "restricted engine ready (no runtime toolchain; policy locked to the curated baked set)"
    );
    Ok((engine, locked_hashes))
}

#[cfg(test)]
mod tests {
    use super::*;
    use sasy_policy::service::{PolicyServiceConfig, UserFunctors};

    /// A factory that never succeeds. The engine only calls it when it spawns
    /// an evaluator, which this test does not do.
    fn no_evaluator() -> EvaluatorFactory {
        Arc::new(|| {
            Err(sasy_policy::EvaluatorError::InitError(
                "not spawned in this test".into(),
            ))
        })
    }

    /// The engine this build serves from must carry the operator's decisions,
    /// not the conservative default. Without them the lazy install — the path
    /// that compiles a persisted policy on first dispatch — would answer the
    /// custom-functor question from `PolicyServiceConfig::default()` while the
    /// service's eager replay answered it from the operator's settings, and
    /// the two load paths in one process would disagree.
    #[tokio::test]
    async fn the_engine_carries_the_operators_decisions() {
        let graph = Arc::new(GraphStore::new(None).unwrap());
        let engine = engine_with_config(
            no_evaluator(),
            graph,
            sasy_policy::session_evaluator::EvaluationDeadlines::from_env(),
            PolicyServiceConfig {
                user_functors: UserFunctors::Unsandboxed,
                sandbox_available: Some(false),
            },
        );
        assert!(
            matches!(
                engine.policy_service_config().user_functors,
                UserFunctors::Unsandboxed
            ),
            "the lazy-install path must see what the operator configured, \
             not PolicyServiceConfig::default()"
        );
    }
}
