//! Bakes a precompiled policy pack into the binary for restricted builds.
//!
//! When `SASY_POLICY_PACK=<dir>` is set at build time, reads `<dir>/manifest.json`
//! (produced by the `pack-policies` tool) and generates a Rust module that
//! `include_bytes!`-embeds each profile's compiled evaluator executable, its
//! content hash, and the default-profile name. The restricted runtime needs no
//! policy source or compilation toolchain. `restricted.rs` includes the
//! generated module. When the env var is unset (normal dev build), an empty
//! pack is generated so the file always exists.

use std::path::Path;

fn main() {
    println!("cargo:rerun-if-env-changed=SASY_POLICY_PACK");
    let out_dir = std::env::var("OUT_DIR").unwrap();
    let dest = Path::new(&out_dir).join("baked_pack.rs");

    let mut code = String::new();
    code.push_str(
        "// @generated by build.rs — baked policy pack.\n\
         pub struct BakedProfile {\n\
         \x20   pub name: &'static str,\n\
         \x20   pub content_hash: &'static str,\n\
         \x20   pub program: &'static str,\n\
         \x20   pub evaluator: &'static [u8],\n\
         \x20   pub is_default: bool,\n\
         }\n",
    );

    match std::env::var("SASY_POLICY_PACK") {
        Ok(pack_dir) if !pack_dir.is_empty() => {
            let pack = Path::new(&pack_dir);
            println!(
                "cargo:rerun-if-changed={}",
                pack.join("manifest.json").display()
            );
            let manifest_txt = std::fs::read_to_string(pack.join("manifest.json"))
                .unwrap_or_else(|e| panic!("SASY_POLICY_PACK manifest unreadable: {e}"));
            let manifest: serde_json::Value = serde_json::from_str(&manifest_txt).unwrap();
            let default = manifest["default"].as_str().unwrap_or("");
            let profiles = manifest["profiles"].as_array().cloned().unwrap_or_default();

            code.push_str(&format!(
                "pub static DEFAULT_PROFILE: &str = {:?};\n",
                default
            ));
            code.push_str("pub static BAKED_PROFILES: &[BakedProfile] = &[\n");
            for p in &profiles {
                let name = p["name"].as_str().unwrap();
                let hash = p["content_hash"].as_str().unwrap();
                let program = p["program"].as_str().unwrap_or("policy_program");
                let is_default = p["default"].as_bool().unwrap_or(false);
                let elf = pack.join(p["evaluator"].as_str().unwrap());
                println!("cargo:rerun-if-changed={}", elf.display());
                // Only the compiled evaluator executable is baked in, not the .dl
                // source. The curated profiles annotate their DENYLIST relations
                // (not IsAuthorized), so denial messages come from the evaluator
                // itself; no source is needed at runtime.
                code.push_str(&format!(
                    "    BakedProfile {{ name: {:?}, content_hash: {:?}, program: {:?}, \
                     evaluator: include_bytes!({:?}), is_default: {} }},\n",
                    name,
                    hash,
                    program,
                    elf.to_str().unwrap(),
                    is_default,
                ));
            }
            code.push_str("];\n");
        }
        _ => {
            // No pack baked in (dev/full build).
            code.push_str("pub static DEFAULT_PROFILE: &str = \"\";\n");
            code.push_str("pub static BAKED_PROFILES: &[BakedProfile] = &[];\n");
        }
    }

    std::fs::write(&dest, code).unwrap();
}
