# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import credential_server_pb2 as credential__server__pb2

GRPC_GENERATED_VERSION = '1.80.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in credential_server_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class CredentialServerStub(object):
    """Per-entity credential store. Credential-injection transforms read from it:
    when a policy authorizes an action and emits ApplyTransform, the reference
    monitor looks up the named credential here and fills it into the outgoing
    request. The tenant is always derived from the authenticated caller.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetCredentials = channel.unary_unary(
                '/CredentialServer/GetCredentials',
                request_serializer=credential__server__pb2.CredentialsRequest.SerializeToString,
                response_deserializer=credential__server__pb2.Credentials.FromString,
                _registered_method=True)
        self.SetCredentials = channel.unary_unary(
                '/CredentialServer/SetCredentials',
                request_serializer=credential__server__pb2.SetCredentialsRequest.SerializeToString,
                response_deserializer=credential__server__pb2.CredentialResponse.FromString,
                _registered_method=True)


class CredentialServerServicer(object):
    """Per-entity credential store. Credential-injection transforms read from it:
    when a policy authorizes an action and emits ApplyTransform, the reference
    monitor looks up the named credential here and fills it into the outgoing
    request. The tenant is always derived from the authenticated caller.
    """

    def GetCredentials(self, request, context):
        """Read the credentials stored for one entity and service.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetCredentials(self, request, context):
        """Store credentials for one entity and service. Every key in the request
        is written, overwriting any value already stored under that key. Keys
        that the request does not mention keep the value they have; this call
        never deletes a stored credential.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_CredentialServerServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetCredentials': grpc.unary_unary_rpc_method_handler(
                    servicer.GetCredentials,
                    request_deserializer=credential__server__pb2.CredentialsRequest.FromString,
                    response_serializer=credential__server__pb2.Credentials.SerializeToString,
            ),
            'SetCredentials': grpc.unary_unary_rpc_method_handler(
                    servicer.SetCredentials,
                    request_deserializer=credential__server__pb2.SetCredentialsRequest.FromString,
                    response_serializer=credential__server__pb2.CredentialResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'CredentialServer', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('CredentialServer', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class CredentialServer(object):
    """Per-entity credential store. Credential-injection transforms read from it:
    when a policy authorizes an action and emits ApplyTransform, the reference
    monitor looks up the named credential here and fills it into the outgoing
    request. The tenant is always derived from the authenticated caller.
    """

    @staticmethod
    def GetCredentials(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/CredentialServer/GetCredentials',
            credential__server__pb2.CredentialsRequest.SerializeToString,
            credential__server__pb2.Credentials.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SetCredentials(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/CredentialServer/SetCredentials',
            credential__server__pb2.SetCredentialsRequest.SerializeToString,
            credential__server__pb2.CredentialResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
