# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: credential_server.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'credential_server.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x17\x63redential_server.proto\"\x8c\x01\n\x15SetCredentialsRequest\x12\x13\n\x06\x65ntity\x18\x01 \x01(\tH\x00\x88\x01\x01\x12\x14\n\x07service\x18\x02 \x01(\tH\x01\x88\x01\x01\x12 \n\x0b\x63redentials\x18\x03 \x03(\x0b\x32\x0b.CredentialB\t\n\x07_entityB\n\n\x08_serviceJ\x04\x08\x04\x10\x05R\ttenant_id\"g\n\x12\x43redentialsRequest\x12\x13\n\x06\x65ntity\x18\x01 \x01(\tH\x00\x88\x01\x01\x12\x14\n\x07service\x18\x02 \x01(\tH\x01\x88\x01\x01\x42\t\n\x07_entityB\n\n\x08_serviceJ\x04\x08\x03\x10\x04R\ttenant_id\"D\n\nCredential\x12\x10\n\x03key\x18\x01 \x01(\tH\x00\x88\x01\x01\x12\x12\n\x05value\x18\x02 \x01(\tH\x01\x88\x01\x01\x42\x06\n\x04_keyB\x08\n\x06_value\"/\n\x0b\x43redentials\x12 \n\x0b\x63redentials\x18\x01 \x03(\x0b\x32\x0b.Credential\"8\n\x12\x43redentialResponse\x12\x15\n\x08response\x18\x01 \x01(\tH\x00\x88\x01\x01\x42\x0b\n\t_response2\x86\x01\n\x10\x43redentialServer\x12\x33\n\x0eGetCredentials\x12\x13.CredentialsRequest\x1a\x0c.Credentials\x12=\n\x0eSetCredentials\x12\x16.SetCredentialsRequest\x1a\x13.CredentialResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'credential_server_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_SETCREDENTIALSREQUEST']._serialized_start=28
  _globals['_SETCREDENTIALSREQUEST']._serialized_end=168
  _globals['_CREDENTIALSREQUEST']._serialized_start=170
  _globals['_CREDENTIALSREQUEST']._serialized_end=273
  _globals['_CREDENTIAL']._serialized_start=275
  _globals['_CREDENTIAL']._serialized_end=343
  _globals['_CREDENTIALS']._serialized_start=345
  _globals['_CREDENTIALS']._serialized_end=392
  _globals['_CREDENTIALRESPONSE']._serialized_start=394
  _globals['_CREDENTIALRESPONSE']._serialized_end=450
  _globals['_CREDENTIALSERVER']._serialized_start=453
  _globals['_CREDENTIALSERVER']._serialized_end=587
# @@protoc_insertion_point(module_scope)
