# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import observability_pb2 as observability__pb2

GRPC_GENERATED_VERSION = '1.80.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in observability_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class ObservabilityStub(object):
    """Records the message dependency graph that policies are evaluated against.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.RegisterEvents = channel.unary_unary(
                '/observability.Observability/RegisterEvents',
                request_serializer=observability__pb2.Events.SerializeToString,
                response_deserializer=observability__pb2.IDs.FromString,
                _registered_method=True)
        self.RegisterDependencies = channel.unary_unary(
                '/observability.Observability/RegisterDependencies',
                request_serializer=observability__pb2.Dependencies.SerializeToString,
                response_deserializer=observability__pb2.Response.FromString,
                _registered_method=True)
        self.RegisterEventsWithDependencies = channel.unary_unary(
                '/observability.Observability/RegisterEventsWithDependencies',
                request_serializer=observability__pb2.EventsWithDependencies.SerializeToString,
                response_deserializer=observability__pb2.IDs.FromString,
                _registered_method=True)
        self.ResolveEvents = channel.unary_unary(
                '/observability.Observability/ResolveEvents',
                request_serializer=observability__pb2.EventSnapshots.SerializeToString,
                response_deserializer=observability__pb2.IDs.FromString,
                _registered_method=True)
        self.ResolveSnapshots = channel.unary_unary(
                '/observability.Observability/ResolveSnapshots',
                request_serializer=observability__pb2.EventSnapshots.SerializeToString,
                response_deserializer=observability__pb2.IDs.FromString,
                _registered_method=True)
        self.BackwardSlice = channel.unary_unary(
                '/observability.Observability/BackwardSlice',
                request_serializer=observability__pb2.SliceRequest.SerializeToString,
                response_deserializer=observability__pb2.Graph.FromString,
                _registered_method=True)
        self.ForwardSlice = channel.unary_unary(
                '/observability.Observability/ForwardSlice',
                request_serializer=observability__pb2.SliceRequest.SerializeToString,
                response_deserializer=observability__pb2.Graph.FromString,
                _registered_method=True)
        self.RegisterComputations = channel.unary_unary(
                '/observability.Observability/RegisterComputations',
                request_serializer=observability__pb2.Computations.SerializeToString,
                response_deserializer=observability__pb2.IDs.FromString,
                _registered_method=True)
        self.GetTrace = channel.unary_unary(
                '/observability.Observability/GetTrace',
                request_serializer=observability__pb2.TraceRequest.SerializeToString,
                response_deserializer=observability__pb2.TraceGraph.FromString,
                _registered_method=True)
        self.GetSpan = channel.unary_unary(
                '/observability.Observability/GetSpan',
                request_serializer=observability__pb2.SpanRequest.SerializeToString,
                response_deserializer=observability__pb2.Computation.FromString,
                _registered_method=True)


class ObservabilityServicer(object):
    """Records the message dependency graph that policies are evaluated against.
    """

    def RegisterEvents(self, request, context):
        """Record messages (graph nodes). Returns one ID per recorded event, in
        order: the caller's `Event.id` when set, otherwise a server-generated
        UUID. An event with no content at all — no text, tools, role, agent,
        entity or derived_from — records nothing and gets an empty string in
        its place, and a batch of nothing but such events records nothing and
        returns an empty list.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RegisterDependencies(self, request, context):
        """Record edges between already-recorded messages.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RegisterEventsWithDependencies(self, request, context):
        """Combined: register events and dependencies in a single atomic transaction
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ResolveEvents(self, request, context):
        """Atomically resolve full immutable message snapshots. IDs preserve input order.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ResolveSnapshots(self, request, context):
        """Full snapshots and validated compact references. A server without this
        RPC returns UNIMPLEMENTED.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def BackwardSlice(self, request, context):
        """The message plus everything it transitively depends on: its ancestry,
        which is what policies see.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ForwardSlice(self, request, context):
        """Everything that transitively depends on the message.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RegisterComputations(self, request, context):
        """Computation/Span operations (OpenTelemetry)
        Record computations (spans): the units of work that produced messages.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetTrace(self, request, context):
        """Every computation of one trace, with the edges between them.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetSpan(self, request, context):
        """One computation by id.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ObservabilityServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'RegisterEvents': grpc.unary_unary_rpc_method_handler(
                    servicer.RegisterEvents,
                    request_deserializer=observability__pb2.Events.FromString,
                    response_serializer=observability__pb2.IDs.SerializeToString,
            ),
            'RegisterDependencies': grpc.unary_unary_rpc_method_handler(
                    servicer.RegisterDependencies,
                    request_deserializer=observability__pb2.Dependencies.FromString,
                    response_serializer=observability__pb2.Response.SerializeToString,
            ),
            'RegisterEventsWithDependencies': grpc.unary_unary_rpc_method_handler(
                    servicer.RegisterEventsWithDependencies,
                    request_deserializer=observability__pb2.EventsWithDependencies.FromString,
                    response_serializer=observability__pb2.IDs.SerializeToString,
            ),
            'ResolveEvents': grpc.unary_unary_rpc_method_handler(
                    servicer.ResolveEvents,
                    request_deserializer=observability__pb2.EventSnapshots.FromString,
                    response_serializer=observability__pb2.IDs.SerializeToString,
            ),
            'ResolveSnapshots': grpc.unary_unary_rpc_method_handler(
                    servicer.ResolveSnapshots,
                    request_deserializer=observability__pb2.EventSnapshots.FromString,
                    response_serializer=observability__pb2.IDs.SerializeToString,
            ),
            'BackwardSlice': grpc.unary_unary_rpc_method_handler(
                    servicer.BackwardSlice,
                    request_deserializer=observability__pb2.SliceRequest.FromString,
                    response_serializer=observability__pb2.Graph.SerializeToString,
            ),
            'ForwardSlice': grpc.unary_unary_rpc_method_handler(
                    servicer.ForwardSlice,
                    request_deserializer=observability__pb2.SliceRequest.FromString,
                    response_serializer=observability__pb2.Graph.SerializeToString,
            ),
            'RegisterComputations': grpc.unary_unary_rpc_method_handler(
                    servicer.RegisterComputations,
                    request_deserializer=observability__pb2.Computations.FromString,
                    response_serializer=observability__pb2.IDs.SerializeToString,
            ),
            'GetTrace': grpc.unary_unary_rpc_method_handler(
                    servicer.GetTrace,
                    request_deserializer=observability__pb2.TraceRequest.FromString,
                    response_serializer=observability__pb2.TraceGraph.SerializeToString,
            ),
            'GetSpan': grpc.unary_unary_rpc_method_handler(
                    servicer.GetSpan,
                    request_deserializer=observability__pb2.SpanRequest.FromString,
                    response_serializer=observability__pb2.Computation.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'observability.Observability', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('observability.Observability', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class Observability(object):
    """Records the message dependency graph that policies are evaluated against.
    """

    @staticmethod
    def RegisterEvents(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/observability.Observability/RegisterEvents',
            observability__pb2.Events.SerializeToString,
            observability__pb2.IDs.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RegisterDependencies(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/observability.Observability/RegisterDependencies',
            observability__pb2.Dependencies.SerializeToString,
            observability__pb2.Response.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RegisterEventsWithDependencies(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/observability.Observability/RegisterEventsWithDependencies',
            observability__pb2.EventsWithDependencies.SerializeToString,
            observability__pb2.IDs.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ResolveEvents(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/observability.Observability/ResolveEvents',
            observability__pb2.EventSnapshots.SerializeToString,
            observability__pb2.IDs.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ResolveSnapshots(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/observability.Observability/ResolveSnapshots',
            observability__pb2.EventSnapshots.SerializeToString,
            observability__pb2.IDs.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def BackwardSlice(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/observability.Observability/BackwardSlice',
            observability__pb2.SliceRequest.SerializeToString,
            observability__pb2.Graph.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ForwardSlice(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/observability.Observability/ForwardSlice',
            observability__pb2.SliceRequest.SerializeToString,
            observability__pb2.Graph.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RegisterComputations(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/observability.Observability/RegisterComputations',
            observability__pb2.Computations.SerializeToString,
            observability__pb2.IDs.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetTrace(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/observability.Observability/GetTrace',
            observability__pb2.TraceRequest.SerializeToString,
            observability__pb2.TraceGraph.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetSpan(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/observability.Observability/GetSpan',
            observability__pb2.SpanRequest.SerializeToString,
            observability__pb2.Computation.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class ObservabilityUpdatesStub(object):
    """Updates service for graph state streaming
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetState = channel.unary_unary(
                '/observability.ObservabilityUpdates/GetState',
                request_serializer=observability__pb2.StateRequest.SerializeToString,
                response_deserializer=observability__pb2.GraphState.FromString,
                _registered_method=True)
        self.StreamUpdates = channel.stream_stream(
                '/observability.ObservabilityUpdates/StreamUpdates',
                request_serializer=observability__pb2.StreamMessage.SerializeToString,
                response_deserializer=observability__pb2.GraphUpdates.FromString,
                _registered_method=True)


class ObservabilityUpdatesServicer(object):
    """Updates service for graph state streaming
    """

    def GetState(self, request, context):
        """Get current graph state
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StreamUpdates(self, request_iterator, context):
        """Bidirectional stream: client sends StreamMessage (subscribe/ack), server sends batched updates
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ObservabilityUpdatesServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetState': grpc.unary_unary_rpc_method_handler(
                    servicer.GetState,
                    request_deserializer=observability__pb2.StateRequest.FromString,
                    response_serializer=observability__pb2.GraphState.SerializeToString,
            ),
            'StreamUpdates': grpc.stream_stream_rpc_method_handler(
                    servicer.StreamUpdates,
                    request_deserializer=observability__pb2.StreamMessage.FromString,
                    response_serializer=observability__pb2.GraphUpdates.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'observability.ObservabilityUpdates', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('observability.ObservabilityUpdates', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ObservabilityUpdates(object):
    """Updates service for graph state streaming
    """

    @staticmethod
    def GetState(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/observability.ObservabilityUpdates/GetState',
            observability__pb2.StateRequest.SerializeToString,
            observability__pb2.GraphState.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StreamUpdates(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(
            request_iterator,
            target,
            '/observability.ObservabilityUpdates/StreamUpdates',
            observability__pb2.StreamMessage.SerializeToString,
            observability__pb2.GraphUpdates.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
