# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import policy_engine_pb2 as policy__engine__pb2

GRPC_GENERATED_VERSION = '1.80.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in policy_engine_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class PolicyEngineStub(object):
    """Policy Engine service for authorization and administration
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CheckAuthorization = channel.unary_unary(
                '/policy_engine.PolicyEngine/CheckAuthorization',
                request_serializer=policy__engine__pb2.AuthorizationRequest.SerializeToString,
                response_deserializer=policy__engine__pb2.AuthorizationResponse.FromString,
                _registered_method=True)
        self.GetSyncStatus = channel.unary_unary(
                '/policy_engine.PolicyEngine/GetSyncStatus',
                request_serializer=policy__engine__pb2.SyncStatusRequest.SerializeToString,
                response_deserializer=policy__engine__pb2.SyncStatusResponse.FromString,
                _registered_method=True)
        self.Health = channel.unary_unary(
                '/policy_engine.PolicyEngine/Health',
                request_serializer=policy__engine__pb2.HealthRequest.SerializeToString,
                response_deserializer=policy__engine__pb2.HealthResponse.FromString,
                _registered_method=True)
        self.SetPolicy = channel.unary_unary(
                '/policy_engine.PolicyEngine/SetPolicy',
                request_serializer=policy__engine__pb2.SetPolicyRequest.SerializeToString,
                response_deserializer=policy__engine__pb2.SetPolicyResponse.FromString,
                _registered_method=True)
        self.GetEvaluatorStatus = channel.unary_unary(
                '/policy_engine.PolicyEngine/GetEvaluatorStatus',
                request_serializer=policy__engine__pb2.EvaluatorStatusRequest.SerializeToString,
                response_deserializer=policy__engine__pb2.EvaluatorStatusResponse.FromString,
                _registered_method=True)
        self.ValidatePolicy = channel.unary_unary(
                '/policy_engine.PolicyEngine/ValidatePolicy',
                request_serializer=policy__engine__pb2.ValidatePolicyRequest.SerializeToString,
                response_deserializer=policy__engine__pb2.ValidatePolicyResponse.FromString,
                _registered_method=True)
        self.EndSession = channel.unary_unary(
                '/policy_engine.PolicyEngine/EndSession',
                request_serializer=policy__engine__pb2.EndSessionRequest.SerializeToString,
                response_deserializer=policy__engine__pb2.EndSessionResponse.FromString,
                _registered_method=True)
        self.UpdatePolicyMetadata = channel.unary_unary(
                '/policy_engine.PolicyEngine/UpdatePolicyMetadata',
                request_serializer=policy__engine__pb2.UpdatePolicyMetadataRequest.SerializeToString,
                response_deserializer=policy__engine__pb2.UpdatePolicyMetadataResponse.FromString,
                _registered_method=True)


class PolicyEngineServicer(object):
    """Policy Engine service for authorization and administration
    """

    def CheckAuthorization(self, request, context):
        """Check authorization for one or more actions
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetSyncStatus(self, request, context):
        """Get current synchronization status
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Health(self, request, context):
        """Health check
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetPolicy(self, request, context):
        """Apply a policy to a target scope:

        * scope.session(session_id="conv-1") — bind a single
        session. Empty session_id = the per-tenant global
        session.
        * scope.default() — set the tenant's default policy for
        newly-spawned unpinned sessions. Existing sessions keep
        their bindings — gradual rollout.
        * scope.force() — set the tenant default *and* evict every
        live session in the tenant. They re-bind to the new
        default on next traffic. Disruptive — break-glass /
        emergency reload.

        Server hashes (`source ‖ functors ‖ backend ‖ ...`) so
        identical re-uploads are free (same content → same registry
        entry, no recompile). The returned policy_id is informational
        — clients address policies by source, not by id.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetEvaluatorStatus(self, request, context):
        """Get the current evaluator backend status
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ValidatePolicy(self, request, context):
        """Validate policy source without applying it
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def EndSession(self, request, context):
        """End a session: release its evaluator, policy binding, session metadata
        and ownership. Recorded graph observations remain in the store.
        Reusing the id does not retain its former policy or approvals.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdatePolicyMetadata(self, request, context):
        """Append dynamic, session-scoped PolicyMetadata facts mid-session
        (for example a user's approval of an `@ask` decision). Append-only:
        facts accumulate
        and persist; the policy resolves any conflict by precedence. The
        facts are pushed into the live evaluator and re-seeded on respawn.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_PolicyEngineServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CheckAuthorization': grpc.unary_unary_rpc_method_handler(
                    servicer.CheckAuthorization,
                    request_deserializer=policy__engine__pb2.AuthorizationRequest.FromString,
                    response_serializer=policy__engine__pb2.AuthorizationResponse.SerializeToString,
            ),
            'GetSyncStatus': grpc.unary_unary_rpc_method_handler(
                    servicer.GetSyncStatus,
                    request_deserializer=policy__engine__pb2.SyncStatusRequest.FromString,
                    response_serializer=policy__engine__pb2.SyncStatusResponse.SerializeToString,
            ),
            'Health': grpc.unary_unary_rpc_method_handler(
                    servicer.Health,
                    request_deserializer=policy__engine__pb2.HealthRequest.FromString,
                    response_serializer=policy__engine__pb2.HealthResponse.SerializeToString,
            ),
            'SetPolicy': grpc.unary_unary_rpc_method_handler(
                    servicer.SetPolicy,
                    request_deserializer=policy__engine__pb2.SetPolicyRequest.FromString,
                    response_serializer=policy__engine__pb2.SetPolicyResponse.SerializeToString,
            ),
            'GetEvaluatorStatus': grpc.unary_unary_rpc_method_handler(
                    servicer.GetEvaluatorStatus,
                    request_deserializer=policy__engine__pb2.EvaluatorStatusRequest.FromString,
                    response_serializer=policy__engine__pb2.EvaluatorStatusResponse.SerializeToString,
            ),
            'ValidatePolicy': grpc.unary_unary_rpc_method_handler(
                    servicer.ValidatePolicy,
                    request_deserializer=policy__engine__pb2.ValidatePolicyRequest.FromString,
                    response_serializer=policy__engine__pb2.ValidatePolicyResponse.SerializeToString,
            ),
            'EndSession': grpc.unary_unary_rpc_method_handler(
                    servicer.EndSession,
                    request_deserializer=policy__engine__pb2.EndSessionRequest.FromString,
                    response_serializer=policy__engine__pb2.EndSessionResponse.SerializeToString,
            ),
            'UpdatePolicyMetadata': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdatePolicyMetadata,
                    request_deserializer=policy__engine__pb2.UpdatePolicyMetadataRequest.FromString,
                    response_serializer=policy__engine__pb2.UpdatePolicyMetadataResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'policy_engine.PolicyEngine', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('policy_engine.PolicyEngine', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class PolicyEngine(object):
    """Policy Engine service for authorization and administration
    """

    @staticmethod
    def CheckAuthorization(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/policy_engine.PolicyEngine/CheckAuthorization',
            policy__engine__pb2.AuthorizationRequest.SerializeToString,
            policy__engine__pb2.AuthorizationResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetSyncStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/policy_engine.PolicyEngine/GetSyncStatus',
            policy__engine__pb2.SyncStatusRequest.SerializeToString,
            policy__engine__pb2.SyncStatusResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Health(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/policy_engine.PolicyEngine/Health',
            policy__engine__pb2.HealthRequest.SerializeToString,
            policy__engine__pb2.HealthResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SetPolicy(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/policy_engine.PolicyEngine/SetPolicy',
            policy__engine__pb2.SetPolicyRequest.SerializeToString,
            policy__engine__pb2.SetPolicyResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetEvaluatorStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/policy_engine.PolicyEngine/GetEvaluatorStatus',
            policy__engine__pb2.EvaluatorStatusRequest.SerializeToString,
            policy__engine__pb2.EvaluatorStatusResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ValidatePolicy(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/policy_engine.PolicyEngine/ValidatePolicy',
            policy__engine__pb2.ValidatePolicyRequest.SerializeToString,
            policy__engine__pb2.ValidatePolicyResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def EndSession(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/policy_engine.PolicyEngine/EndSession',
            policy__engine__pb2.EndSessionRequest.SerializeToString,
            policy__engine__pb2.EndSessionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdatePolicyMetadata(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/policy_engine.PolicyEngine/UpdatePolicyMetadata',
            policy__engine__pb2.UpdatePolicyMetadataRequest.SerializeToString,
            policy__engine__pb2.UpdatePolicyMetadataResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
