# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import reference_monitor_pb2 as reference__monitor__pb2

GRPC_GENERATED_VERSION = '1.80.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in reference_monitor_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class RMProxyStub(object):
    """Reference monitor: the enforcement point an agent runtime calls before it
    executes an action. Each decision evaluates the session's bound policy over
    the ancestry of the requesting messages.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ProxyHTTP = channel.stream_stream(
                '/RMProxy/ProxyHTTP',
                request_serializer=reference__monitor__pb2.HTTPRequest.SerializeToString,
                response_deserializer=reference__monitor__pb2.HTTPResponse.FromString,
                _registered_method=True)
        self.CheckToolCall = channel.unary_unary(
                '/RMProxy/CheckToolCall',
                request_serializer=reference__monitor__pb2.ToolCallRequest.SerializeToString,
                response_deserializer=reference__monitor__pb2.ToolCallResponse.FromString,
                _registered_method=True)


class RMProxyServicer(object):
    """Reference monitor: the enforcement point an agent runtime calls before it
    executes an action. Each decision evaluates the session's bound policy over
    the ancestry of the requesting messages.
    """

    def ProxyHTTP(self, request_iterator, context):
        """Forward HTTP requests through the monitor. Each request is authorized as
        an HTTPRequest action; an authorized request is sent upstream after any
        credential-injection transforms. An unauthorized request gets an error
        response, unless the policy's `AllowPassthrough` relation holds for it,
        in which case it is forwarded unchanged and without transforms.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CheckToolCall(self, request, context):
        """Decide whether one tool call may run. Call it BEFORE executing the tool;
        the monitor never executes it. A denial is a response, not a gRPC error.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_RMProxyServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ProxyHTTP': grpc.stream_stream_rpc_method_handler(
                    servicer.ProxyHTTP,
                    request_deserializer=reference__monitor__pb2.HTTPRequest.FromString,
                    response_serializer=reference__monitor__pb2.HTTPResponse.SerializeToString,
            ),
            'CheckToolCall': grpc.unary_unary_rpc_method_handler(
                    servicer.CheckToolCall,
                    request_deserializer=reference__monitor__pb2.ToolCallRequest.FromString,
                    response_serializer=reference__monitor__pb2.ToolCallResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'RMProxy', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('RMProxy', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class RMProxy(object):
    """Reference monitor: the enforcement point an agent runtime calls before it
    executes an action. Each decision evaluates the session's bound policy over
    the ancestry of the requesting messages.
    """

    @staticmethod
    def ProxyHTTP(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(
            request_iterator,
            target,
            '/RMProxy/ProxyHTTP',
            reference__monitor__pb2.HTTPRequest.SerializeToString,
            reference__monitor__pb2.HTTPResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CheckToolCall(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/RMProxy/CheckToolCall',
            reference__monitor__pb2.ToolCallRequest.SerializeToString,
            reference__monitor__pb2.ToolCallResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
